In [4]:
my_list = [1,2,3,4]

In [5]:
import numpy as np

In [6]:
np.array(my_list)

array([1, 2, 3, 4])

In [7]:
np.array([[1,2,3,4], [5,2,3,4]])

array([[1, 2, 3, 4],
       [5, 2, 3, 4]])

In [8]:
np.arange(0, 5)
# np.arange(0, 5, 2)

array([0, 1, 2, 3, 4])

In [9]:
np.random.randn(3)

array([-2.89826145, -1.21333896,  0.27625141])

In [10]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.random.randint(0, 5, 5)

array([0, 4, 3, 2, 2])

In [12]:
arr = np.random.randint(0, 6, 4)

In [13]:
arr

array([2, 5, 5, 5])

In [14]:
arr1 = arr.reshape(2,2)

In [15]:
arr1.reshape(4)

array([2, 5, 5, 5])

In [16]:
print(arr.shape)
arr1.shape

(4,)


(2, 2)

In [17]:
print(arr.argmax())
arr.max()


1


np.int64(5)

In [18]:
arr

array([2, 5, 5, 5])

In [19]:
print(arr.argmin())
arr.min()

0


np.int64(2)

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr = np.arange(0, 6)

In [22]:
arr

array([0, 1, 2, 3, 4, 5])

In [23]:
arr[0:3] = 50

In [24]:
arr

array([50, 50, 50,  3,  4,  5])

In [25]:
arr_sample = arr.copy()

In [26]:
arr_sample[0:3] = 0

In [37]:
arr_sample

array([0, 0, 0, 3, 4, 5])

In [27]:
arr

array([50, 50, 50,  3,  4,  5])

In [28]:
arr_1 = np.array([[5,10,15,20], [21,25,30,45], [35,40,46,50]])

In [29]:
arr_1

array([[ 5, 10, 15, 20],
       [21, 25, 30, 45],
       [35, 40, 46, 50]])

In [30]:
arr_1[1,1]

np.int64(25)

In [31]:
arr_1[:2, 3:]

array([[20],
       [45]])

In [32]:
arr = np.arange(1, 6)

In [33]:
arr

array([1, 2, 3, 4, 5])

In [34]:
arr_bool = arr >= 3

In [35]:
arr_bool

array([False, False,  True,  True,  True])

In [36]:
arr[arr_bool]

array([3, 4, 5])

In [38]:
arr[arr>=3]

array([3, 4, 5])