In [2]:
my_list = [1,2,3,4]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3, 4])

In [6]:
np.array([[1,2,3,4], [5,2,3,4]])

array([[1, 2, 3, 4],
       [5, 2, 3, 4]])

In [11]:
np.arange(0, 5)
# np.arange(0, 5, 2)

array([0, 1, 2, 3, 4])

In [14]:
np.random.randn(3)

array([ 0.533631  ,  0.18438646, -0.30814985])

In [23]:
np.random.randint(0, 5, 5)

array([0, 2, 3, 3, 0])

In [25]:
arr = np.random.randint(0, 6, 4)

In [26]:
arr

array([3, 1, 5, 4])

In [30]:
arr1 = arr.reshape(2,2)

In [35]:
arr1.reshape(4)

array([3, 1, 5, 4])

In [38]:
print(arr.shape)
arr1.shape

(4,)


(2, 2)

In [44]:
print(arr.argmax())
arr.max()


2


np.int64(5)

In [45]:
arr

array([3, 1, 5, 4])

In [46]:
print(arr.argmin())
arr.min()

1


np.int64(1)

In [43]:
arr.dtype

dtype('int64')

In [47]:
arr = np.arange(0, 6)

In [48]:
arr

array([0, 1, 2, 3, 4, 5])

In [50]:
arr[0:3] = 50

In [51]:
arr

array([50, 50, 50,  3,  4,  5])

In [60]:
arr_sample = arr.copy()

In [63]:
arr_sample[0:3] = 0

In [65]:
arr

array([50, 50, 50,  3,  4,  5])

In [67]:
arr_1 = np.array([[5,10,15,20], [21,25,30,45], [35,40,46,50]])

In [68]:
arr_1

array([[ 5, 10, 15, 20],
       [21, 25, 30, 45],
       [35, 40, 46, 50]])

In [69]:
arr_1[1,1]

np.int64(25)

In [71]:
arr_1[:2, 3:]

array([[20],
       [45]])

In [72]:
arr = np.arange(1, 6)

In [73]:
arr

array([1, 2, 3, 4, 5])

In [74]:
arr_bool = arr >= 3

In [75]:
arr_bool

array([False, False,  True,  True,  True])

In [76]:
arr[arr_bool]

array([3, 4, 5])